import { makeStyles } from "@material-ui/core";
export const useStyles  = makeStyles((theme)=>({
        container:{
            display:'flex',
            flexDirection:'column',
            alignItems:'center',
            marginTop:100
        },
        innerContainer:{
            display:'flex',
            flexDirection:'row'
        },
        grow:{
            display:'flex',
            flexDirection:'row',
            flex:1
        },
        toolbarLanguage:{
            display:'flex',
            flexDirection:'row',
            alignItems:'center'
        },
        loginContainer:{
            display:'flex',
            flexDirection:'column',
            padding:30,
            [theme.breakpoints.down('xs')]:{
                padding:10
            }
        },
        divider:{
            width:150
        },
        footer:{
            display:'flex',
            flexDirection:'row',
            alignItems:'center',
            marginTop:130
        },
        text_input:{
            width:'100%',
            marginBottom:25
        },
        logo:{
            display:'flex',
            flexDirection:'row',
            cursor:'pointer'
        },
        first:{
            color:'white',
            textDecoration:'none'
        },
        secondColor:{
            color:"#242424",
            textDecoration:'none'
        },
        second:{
            color:'#ff3d54',
            textDecoration:'none'
        },
        description:{
            color:'white',
            marginTop:25
        },
        routeContainer:{
            marginLeft:100,
            [theme.breakpoints.down('xs')]:{
                marginLeft:0
            }
        },
        allCards:{
            marginLeft:100,
            marginTop:60,
            maxHeight:550,
            height:550,
            [theme.breakpoints.down('xs')]:{
                marginLeft:0,
                height:'100%',
                maxHeight:'100%'
            }
        },
        info:{
            display:'flex',
            flexDirection:'column',
            marginBottom:25,
            marginTop:100,
            [theme.breakpoints.down('xs')]:{
                display:'none'
            }
        },
        routeCard:{
            height:430,
            maxHeight:430,
            [theme.breakpoints.down('xs')]:{
                maxHeight:'100%'
            }
        },
        languageMenu:{
            display:'flex',
            flexDirection:'row',
            alignItems:'center',
            marginLeft:160,
            backgroundColor:'rgba(0,0,0,0.3)',
            padding:5
        },
        smallDevice:{
            display:'flex',
            [theme.breakpoints.down('xs')]:{
                display:'none'
            }
        },
        languageOnSmallDevice:{
            display:'none',
            [theme.breakpoints.down('xs')]:{
                display:'flex',
                marginTop:25
            }
        },
        languageBtn:{
            color:'white',
            textTransform:'none'
        },
        toolBarContainer:{
            display:'flex',
            flexDirection:'row'
        },
        toolBarButtons:{
            color:'white',
            textTransform:'none'
        },
        secondToolBarButtons:{
            color:'#242424',
            textTransform:'none'
        },
        grow:{
            display:'flex',
            flexDirection:'row',
            flexGrow:1
        },
        mainContainer:{
            marginTop:50,
            padding:20
        },
        howItWorksContainer:{
            display:'flex',
            flexDirection:'column',

        },
        margin:{
            marginTop:75
        }
}))

export default useStyles